### ISSUE TITLE
Broken `rnpkeys --keystore-format=SSH --list-keys`

### ISSUE THREAD

**Issue by catap** [riboseinc/rnp#303]
## Description
```sh
➜  rnp git:(master) ./src/rnpkeys/rnpkeys --keystore-format=SSH --list-keys
rnp: unsupported keystore format: "1"
fatal: cannot apply configuration
rnpkeys(81511,0x7fffe466d3c0) malloc: *** error for object 0x616d726f662d6572: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    81511 abort      ./src/rnpkeys/rnpkeys --keystore-format=SSH --list-keys
➜
```
## Steps to Reproduce

1. get last master
2. build it
3. run `./src/rnpkeys/rnpkeys --keystore-format=SSH --list-keys`

## Expected Behavior

Something likes:
```sh
./src/rnpkeys/rnpkeys --keystore-format=SSH --list-keys
1 key found
signature  2048/RSA (Encrypt or Sign) 78f54270acf21f6a 1970-01-01
Key fingerprint: dacb0c54f989e60578f54270acf21f6a
uid              Kirills-MacBookPro.local (/Users/catap/.ssh/id_rsa.pub) <catap@satellite> 
```

## Actual Behavior

unsupported SSH keystore format and crash.

for example at https://github.com/riboseinc/rnp/commit/1c3a1cd6594767cb935eba4b1c78a2ebc77328c2 I had only `unsupported keystore format: "1"`
```sh
 ➜  rnp git:(1c3a1cd) ✗ ./src/rnpkeys/rnpkeys --keystore-format=SSH --list-keys
rnp: unsupported keystore format: "1"
fatal: cannot apply configuration
```

**Comment by dewyatt** [comment]
Would you be able to do a bisect and find where it broke?

@ronaldtse Would a `regression` label be useful here? (I think you're the only one that can create new labels.)

**Comment by catap** [comment]
@dewyatt I'm on it :)

**Comment by ni4** [comment]
SSH keystore is definitely not supported in current master. I'm going to fix it in #299 , and it would be logical to add tests for it during the work on #294. So, basically, I can handle this.

**Comment by catap** [comment]
@ni4 but returns `unsupported keystore format: "1"` looks strange, isn't it?

**Comment by catap** [comment]
I can't find the exaclity commit that it broke because I can't build any commit :( sometime it can't build with errors like:
```
In file included from create.c:96:
./rnpsdk.h:80:12: error: unused function 'grabdate' [-Werror,-Wunused-function]
static int grabdate(char *s, int64_t *t);
           ^
./rnpsdk.h:81:17: error: unused function 'get_duration' [-Werror,-Wunused-function]
static uint64_t get_duration(char *s);
                ^
./rnpsdk.h:82:16: error: unused function 'get_birthtime' [-Werror,-Wunused-function]
static int64_t get_birthtime(char *s);
               ^
3 errors generated.
```
or
```
brnp_la-key_store_pgp.o
key_store_pgp.c:147:21: error: implicit declaration of function 'rnp_getvar' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if ((filename = rnp_getvar(rnp, name)) == NULL) {
                    ^
key_store_pgp.c:147:19: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Werror,-Wint-conversion]
    if ((filename = rnp_getvar(rnp, name)) == NULL) {
                  ^ ~~~~~~~~~~~~~~~~~~~~~
key_store_pgp.c:160:5: error: implicit declaration of function 'rnp_setvar' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    rnp_setvar(rnp, name, filename);
    ^
key_store_pgp.c:160:5: note: did you mean 'rnp_getvar'?
key_store_pgp.c:147:21: note: 'rnp_getvar' declared here
    if ((filename = rnp_getvar(rnp, name)) == NULL) {
                    ^
key_store_pgp.c:191:17: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Werror,-Wint-conversion]
    if ((userid = rnp_getvar(rnp, "userid")) == NULL) {
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
key_store_pgp.c:217:55: error: comparison between pointer and integer ('int' and 'void *') [-Werror]
        if (!userid && rnp_getvar(rnp, "need userid") != NULL) {
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~
key_store_pgp.c:230:47: error: comparison between pointer and integer ('int' and 'void *') [-Werror]
    } else if (rnp_getvar(rnp, "need userid") != NULL) {
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~
6 errors generated.
```

I used `./build_macos.sh` to build it and I expect that it should build after each commit.

Anyway, if we skip all commits that can't be build, `git bisect` has response:
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
aa0a09aa23787acb7f444877da44bfeac0916ca3
28d16eeeccb382b6f5b1903f7c850ee11bfa0665
8e45f9a154c6757ed38f3081be7e59767b9527bc
4546b34ba9ca028bef3022784efa4a54a7bd7b5e
c76236926c857f761e07e801c3089f4a954b0725
7903a25d25fb720d7b8066a54b83bb7634c48fd0
cd6958461910e03936be363ed4b4571c22ce12f8
91df1f89d3de16b8f2d89d02ffbfd1f48e70e558
a3782743f943bdac08d21c90c9901d8508565fa7
56ded194212ac20b940bb14d57267a1c7effc6f7
8abd4b6b89e4cff786e920f436f57078d9aae118
31744e8234972d7d729447d085cf93f2c1cdadb8
5cf032687df0f2235bd405ddd518acf16ae8391d
ea1eb788f4736f5fb4daa7ad0d5cddc62f7d186f
We cannot bisect more!
``` 

I also attached bisect log where you can see that commit I can't build (it was marked as skipt):
```
git bisect start
# good: [c09f27074fc4bd160d746f60246960d571840395] Merge pull request #264 from flowher/generate_rigth_curve
git bisect good c09f27074fc4bd160d746f60246960d571840395
# bad: [47262a26122e94294471de3d9ebbe198fdf8a0cb] Merge pull request #296 from flowher/refactoring_fixes
git bisect bad 47262a26122e94294471de3d9ebbe198fdf8a0cb
# bad: [1c3a1cd6594767cb935eba4b1c78a2ebc77328c2] Merge pull request #268 from riboseinc/incompleteio
git bisect bad 1c3a1cd6594767cb935eba4b1c78a2ebc77328c2
# bad: [2b9d579227eb5569ce26f462a98f1991da72f21c] Fixed checking of the default user id
git bisect bad 2b9d579227eb5569ce26f462a98f1991da72f21c
# skip: [8e45f9a154c6757ed38f3081be7e59767b9527bc] Refactored passfd and rnpio to not use rnp_getvar.
git bisect skip 8e45f9a154c6757ed38f3081be7e59767b9527bc
# skip: [31744e8234972d7d729447d085cf93f2c1cdadb8] Updated rnpkeys to the new interfaces.
git bisect skip 31744e8234972d7d729447d085cf93f2c1cdadb8
# skip: [4546b34ba9ca028bef3022784efa4a54a7bd7b5e] Some more updates to the rnp_cfg_apply method; Removed some obsolet rnp_setvar/rnp_getvar calls.
git bisect skip 4546b34ba9ca028bef3022784efa4a54a7bd7b5e
# skip: [cd6958461910e03936be363ed4b4571c22ce12f8] Removed rnp_getvar for coredumps.
git bisect skip cd6958461910e03936be363ed4b4571c22ce12f8
# skip: [aa0a09aa23787acb7f444877da44bfeac0916ca3] Merge branch 'master' into ni4-245-refactor-rnp-config
git bisect skip aa0a09aa23787acb7f444877da44bfeac0916ca3
# skip: [a3782743f943bdac08d21c90c9901d8508565fa7] Now rnp_ctx_t is the main parameter for all high-level crypto calls, and has pointer to the rnp_t; Removed some more rnp_getvar/setvar dependency; Not buildable yet.
git bisect skip a3782743f943bdac08d21c90c9901d8508565fa7
# skip: [28d16eeeccb382b6f5b1903f7c850ee11bfa0665] Moved sig date helper functions to the better place.
git bisect skip 28d16eeeccb382b6f5b1903f7c850ee11bfa0665
# skip: [56ded194212ac20b940bb14d57267a1c7effc6f7] Fixed numerous compilation issues.
git bisect skip 56ded194212ac20b940bb14d57267a1c7effc6f7
# skip: [7903a25d25fb720d7b8066a54b83bb7634c48fd0] Merge branch 'master' into ni4-245-refactor-rnp-config
git bisect skip 7903a25d25fb720d7b8066a54b83bb7634c48fd0
# bad: [ea1eb788f4736f5fb4daa7ad0d5cddc62f7d186f] Fixed cmocka tests to be compatible with new rnp interfaces.
git bisect bad ea1eb788f4736f5fb4daa7ad0d5cddc62f7d186f
# skip: [91df1f89d3de16b8f2d89d02ffbfd1f48e70e558] Cleanup up obsolete keyring path/type detection code.
git bisect skip 91df1f89d3de16b8f2d89d02ffbfd1f48e70e558
# skip: [c76236926c857f761e07e801c3089f4a954b0725] Removed rnp_getvar for hash algorithm and signature creation/duration
git bisect skip c76236926c857f761e07e801c3089f4a954b0725
# skip: [8abd4b6b89e4cff786e920f436f57078d9aae118] Merge branch 'master' into ni4-245-refactor-rnp-config
git bisect skip 8abd4b6b89e4cff786e920f436f57078d9aae118
# skip: [5cf032687df0f2235bd405ddd518acf16ae8391d] Moved all user-defined variables into separate CLI-level rnp_cfg_t type.
git bisect skip 5cf032687df0f2235bd405ddd518acf16ae8391d
# only skipped commits left to test
# possible first bad commit: [ea1eb788f4736f5fb4daa7ad0d5cddc62f7d186f] Fixed cmocka tests to be compatible with new rnp interfaces.
# possible first bad commit: [31744e8234972d7d729447d085cf93f2c1cdadb8] Updated rnpkeys to the new interfaces.
# possible first bad commit: [56ded194212ac20b940bb14d57267a1c7effc6f7] Fixed numerous compilation issues.
# possible first bad commit: [91df1f89d3de16b8f2d89d02ffbfd1f48e70e558] Cleanup up obsolete keyring path/type detection code.
# possible first bad commit: [7903a25d25fb720d7b8066a54b83bb7634c48fd0] Merge branch 'master' into ni4-245-refactor-rnp-config
# possible first bad commit: [4546b34ba9ca028bef3022784efa4a54a7bd7b5e] Some more updates to the rnp_cfg_apply method; Removed some obsolet rnp_setvar/rnp_getvar calls.
# possible first bad commit: [8e45f9a154c6757ed38f3081be7e59767b9527bc] Refactored passfd and rnpio to not use rnp_getvar.
# possible first bad commit: [aa0a09aa23787acb7f444877da44bfeac0916ca3] Merge branch 'master' into ni4-245-refactor-rnp-config
# possible first bad commit: [28d16eeeccb382b6f5b1903f7c850ee11bfa0665] Moved sig date helper functions to the better place.
# possible first bad commit: [c76236926c857f761e07e801c3089f4a954b0725] Removed rnp_getvar for hash algorithm and signature creation/duration
# possible first bad commit: [cd6958461910e03936be363ed4b4571c22ce12f8] Removed rnp_getvar for coredumps.
# possible first bad commit: [a3782743f943bdac08d21c90c9901d8508565fa7] Now rnp_ctx_t is the main parameter for all high-level crypto calls, and has pointer to the rnp_t; Removed some more rnp_getvar/setvar dependency; Not buildable yet.
# possible first bad commit: [8abd4b6b89e4cff786e920f436f57078d9aae118] Merge branch 'master' into ni4-245-refactor-rnp-config
# possible first bad commit: [5cf032687df0f2235bd405ddd518acf16ae8391d] Moved all user-defined variables into separate CLI-level rnp_cfg_t type.

```

**Comment by ni4** [comment]
@catap This is the error it should return - since when I think that we should cut out SSH keys support I #ifdef'ed SSH keys load with ENABLE_SSH, and otherwise was returning error. So it's kinda ok. Anyway, working on this now

**Comment by catap** [comment]
@ni4 and can you made each commit builded?

**Comment by ni4** [comment]
All final commits to the PR are/were compilable, but commits between them which were not squashed probably were non-buildable. Also sometimes it do not build if you don't ./remove_artifacts.sh

**Comment by catap** [comment]
@ni4, but it brokes `git bisect`!

**Comment by dewyatt** [comment]
> All final commits to the PR are/were compilable, but commits between them which were not squashed probably were non-buildable. Also sometimes it do not build if you don't ./remove_artifacts.sh

I've noticed this too, it's always worth trying `make clean && make distclean` or `./remove_artifacts.sh` and `autoreconf`, etc.

**Comment by flowher** [comment]
Isn't it why we have travis to do it for us?

**Comment by catap** [comment]
@flowher travis checking only tests and RNP hasn't got 100% covering by tests ;)

`git bisect` helps to find a commit that broke something (or made performance degradation) and it's very sad when it returns 10+ commits becuase part of them can't be build and checked. So, someone should check it by hand/eye.

**Comment by flowher** [comment]
@catap good point

**Comment by catap** [comment]
@ni4, also I expect that it returns: `unsupported keystore format: "SSH"` and not `unsupported keystore format: "1"` with crash ;)

**Comment by catap** [comment]
@flowher and sometimes when you should find a very rare bug that appears somewhere between few years — `git bisect` is the only way to do so.

For example: https://github.com/openssl/openssl/issues/1851 — this script works about 5-6 hours because it tested openssl since 0.9.8 or something like this.

**Comment by flowher** [comment]
So, one more thing to add to dev guide. Each commit must compile and be tested.

**Comment by flowher** [comment]
I think it would be better if ``--list-keys`` works in a way that if it doesn't know how to parse the key, it prints an error and continues with the next key instead of t exist with an error).

**Comment by ronaldtse** [comment]
@dewyatt I just added the "regression" label. Great suggestion 👍

**Comment by ni4** [comment]
@catap Can you please confirm that it doesn't or does work with the current master?
Since on my newly generated SSH key it tells the following, and checking back commits it tells the same at least since beginning of June:

```
Nickolays-MacBook-Pro:rnp Ribose$ rnpkeys --keystore-format=SSH --list-keys
256 bytes left
[]
ssh2_readkeys: can't read pubkeys '/Users/Ribose/.ssh/id_rsa.pub'
readsshkeys: cannot read /Users/Ribose/.ssh/id_rsa.pub
cannot read ssh keys
0 keys found
```

**Comment by dewyatt** [comment]
@ni4 FYI I always had that same result unless I replaced the base64 decoder used for SSH keys (`frombase64`), which I believe is broken (mentioned in another issue).

**Comment by ronaldtse** [comment]
@dewyatt @ni4 the related issue to replace the base64 implementation is #16.

**Comment by ni4** [comment]
@dewyatt Thanks. So I will close this issue as it seems to be fixed to the old state via the PR #299

**Comment by catap** [comment]
@ni4 nope, it sitll broken:

```
➜  rnp git:(master) ✗ ./src/rnpkeys/rnpkeys --keystore-format=SSH --list-keys
rnp: default key set to "4E42FC58C5610C1DE8F30895642B66CD6A8959D9"
botan_privkey_load: Invalid argument Decoding error: PKCS #8 private key decoding failed: Invalid argument Decoding error: PKCS #8: Unknown PEM label RSA PRIVATE KEY
rnp PEM /Users/catap/.ssh/id_rsa passphrase: 
```

anyway, I think it's a very bad practice when you ask someone to confirm the fix and close it without answer.

**Comment by ni4** [comment]
@catap actually it fixes the behavior you described in the issue description, isn't it? And, as @dewyatt confirmed, the next problem existed for a long time and related to the #16

**Comment by catap** [comment]
@ni4 nope, it doesn't. See block: Expected Behavior

;)

**Comment by ni4** [comment]
@catap ok. Can you please check whether it works as expected on the 965fb1b ?

**Comment by catap** [comment]
@ni4 yes, it work. Last commit when it works was https://github.com/riboseinc/rnp/commit/c09f27074fc4bd160d746f60246960d571840395

Check my output of `git bisec` ;)

**Comment by ronaldtse** [comment]
@ni4 @dewyatt do we still deal with SSH keys?

**Comment by ni4** [comment]
@ronaldtse I would vote for dropping usage of SSH keys. It adds complexity to the code while doesn't add any benefits, and doesn't seem to be used in other implementations.

**Comment by ni4** [comment]
@ronaldtse @dewyatt So if we agreed on this then I would be happy to remove all SSH-related things.

**Comment by dewyatt** [comment]
@ni4 Volunteering for the dirty work! :+1:

**Comment by ronaldtse** [comment]
Agreed, let's do it. Thanks!
